config/routes.rb
SignalSeeker::Application.routes.draw do
  get "admin/index" => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :data

  get "developer/index"

  get "home/index"

  root :to => 'home#index', :as => 'home'

end

app/controllers/data_controller.rb
class DataController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :show, :new, :create, :destroy, :update]
  # GET /data
  # GET /data.xml
  def index
    @data = Datum.all
    @time = Time.now.strftime("%H:%M %m-%d-%y ")
    
    @data.each do |data|
      data.gmaps = true
      data.update_attributes(:gmaps)
    end
    
    @json = Datum.all.to_gmaps4rails
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @data }
    end
  end

  # GET /data/1
  # GET /data/1.xml
  def show
    @datum = Datum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @datum }
    end
  end

  # GET /data/new
  # GET /data/new.xml
  def new
    @datum = Datum.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @datum }
    end
  end

  # GET /data/1/edit
  def edit
    @datum = Datum.find(params[:id])
  end

  # POST /data
  # POST /data.xml
  def create
    @datum = Datum.new(params[:datum])
    
    if(params[:datum])
      @datum = Datum.new(params[:datum])
    else
      params[:datum] = {:latitude => params[:latitude],
                        :longitude => params[:longitude],
                        :gmaps => params[:gmaps],
                        :location => params[:location],
                        :address => params[:address],
                        :carrier => params[:carrier],
                        :wifi => params[:wifi],
                        :cell => params[:cell]
      }
      @datum = Datum.new(params[:datum])
    end
      
    respond_to do |format|
      if @datum.save
        format.html { redirect_to(@datum, :notice => 'Datum was successfully created.') }
        format.xml  { render :xml => @datum, :status => :created, :location => @datum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /data/1
  # PUT /data/1.xml
  def update
    @datum = Datum.find(params[:id])
    
    if(!params[:datum])
      params[:datum] = {:latitude => params[:latitude],
                        :longitude => params[:longitude],
                        :gmaps => params[:gmaps],
                        :location => params[:location],
                        :address => params[:address],
                        :carrier => params[:carrier],
                        :wifi => params[:wifi],
                        :cell => params[:cell]
      }
    end
    
    
    respond_to do |format|
      if @datum.update_attributes(params[:datum])
        format.html { redirect_to(@datum, :notice => 'Datum was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.xml
  def destroy
    @datum = Datum.find(params[:id])
    @datum.destroy

    respond_to do |format|
      format.html { redirect_to(data_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
<% if @datum.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@datum.errors.count, "error") %> prohibited this data from being saved:</h2>
	<ul>
		<% @datum.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<%= f.label :Location, 'Location name' %>:
	<br />
	<%= f.text_field :location %>
</div>
<div class="field">
	<%= f.label :address, 'Location(Latitude, Longitude)' %>:
	<br />
	<%= f.text_field :address %>
</div>
<div class="field">
	<%= f.label :carrier %>:
	<br />
	<%= f.select :carrier, Datum::CARRIER_TYPES,
    :prompt => 'Select a carrier' %>
</div>
<div class="field">
	<%= f.label :wifi, 'Wifi signal strength' %>:
	<br />
	<%= f.select :wifi, Datum::SIGNAL_STRENGTH,
	 :prompt => 'Select a signal strength'%>
</div>
<div class="field">
	<%= f.label :cell, 'Cell signal strength' %>:
	<br />
	<%= f.select :cell, Datum::SIGNAL_STRENGTH,
	 :prompt => 'Select a signal strength'%>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

app/views/data/edit.html.erb
<div class="section">
	<h1>Editing Datum</h1>
	<%= form_for(@datum) do |f| %>
	<div class="field">
		<%= f.label :location, 'Location name' %>:
		<br />
		<%= f.text_field :location %>
	<div class="field">
		<%= f.label :latitude %>:
		<br />
		<%= f.text_field :latitude %>
	</div>
	<div class="field">
		<%= f.label :longitude %>:
		<br />
		<%= f.text_field :longitude %>
	</div>
	<div class="field">
		<%= f.label :carrier %>:
		<br />
		<%= f.select :carrier, Datum::CARRIER_TYPES,
      	:prompt => 'Select a carrier' %>
	</div>
	<div class="field">
		<%= f.label :wifi, 'Wifi signal strength' %>:
		<br />
		<%= f.select :wifi, Datum::SIGNAL_STRENGTH,
      		:prompt => 'Select a signal strength'%>
	</div>
	<div class="field">
		<%= f.label :cell, 'Cell signal strength' %>:
		<br />
		<%= f.select :cell, Datum::SIGNAL_STRENGTH,
      		:prompt => 'Select a signal strength'%>
	</div>
	<div class="nav">
		<%= f.submit %>
	</div>
	<% end %>
	<br />
	<div class="nav">
		<%= link_to 'Show', @datum %>
		<%= link_to 'Back', data_path %>
	</div>

app/views/data/index.html.erb
<div class="section">
	<h1>Signal Strength and Location Data</h1>
	<table>
		<tr>
			<th>Location name</th>
			<th>Latitude</th>
			<th>Longitude</th>
			<th>Carrier</th>
			<th>Wifi</th>
			<th>Cell</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<% @data.each do |datum| %>
		<tr>
			<td><%= datum.location %></td>
			<td><%= datum.latitude %></td>
			<td><%= datum.longitude %></td>
			<td><%= datum.carrier %></td>
			<td><%= datum.wifi %></td>
			<td><%= datum.cell %></td>
			<td><%= link_to 'Show', datum %></td>
			<td><%= link_to 'Edit', edit_datum_path(datum) %></td>
			<td><%= link_to 'Destroy', datum, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
		<% end %>
	</table>
	<br />
	<div class="nav">
		<%= link_to 'New Datum', new_datum_path %>
	</div>
</div>

app/views/data/new.html.erb
<div class="section">
	<h1>New Datum</h1>
	<h4>Please enter signal and location data</h4>
	<%= render 'form' %>
</div>

app/views/data/show.html.erb
<div class="section">
	<p id="notice">
		<%= notice %>
	</p>
	<h1>Signal Strength and Location Data Details</h1>
	<p>
		<b>Location name:</b>
		<%= @datum.location %>
	</p>
	<p>
		<b>Latitude:</b>
		<%= @datum.latitude %>
	</p>
	<p>
		<b>Longitude:</b>
		<%= @datum.longitude %>
	</p>
	<p>
		<b>Carrier name:</b>
		<%= @datum.carrier %>
	</p>
	<p>
		<b>Wifi signal strength:</b>
		<%= @datum.wifi %>
	</p>
	<p>
		<b>Cell signal strength:</b>
		<%= @datum.cell %>
	</p>
	<div class="nav">
		<%= link_to 'Edit', edit_datum_path(@datum) %>
		<%= link_to 'Back', data_path %>
	</div>